#include "BackupManager.h"

#include "DatabaseManager.h"
#include "FileManager.h"
#include "SQLParser.h"

#include <fstream>
#include <sstream>

#ifdef _WIN32
#include <windows.h>
#else
#include <dirent.h>
#include <unistd.h>
#endif

namespace {
bool directoryExists(const std::string& path) {
    struct stat st;
    return stat(path.c_str(), &st) == 0 && (st.st_mode & S_IFDIR) != 0;
}

#ifdef _WIN32
bool removeDirectoryRecursive(const std::string& path) {
    WIN32_FIND_DATAA findData;
    HANDLE handle = FindFirstFileA((joinPath(path, "*")).c_str(), &findData);
    if (handle != INVALID_HANDLE_VALUE) {
        do {
            const std::string name = findData.cFileName;
            if (name == "." || name == "..") continue;

            const std::string fullPath = joinPath(path, name);
            if ((findData.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) != 0) {
                if (!removeDirectoryRecursive(fullPath)) {
                    FindClose(handle);
                    return false;
                }
            }
            else {
                SetFileAttributesA(fullPath.c_str(), FILE_ATTRIBUTE_NORMAL);
                if (!DeleteFileA(fullPath.c_str())) {
                    FindClose(handle);
                    return false;
                }
            }
        } while (FindNextFileA(handle, &findData) != 0);
        FindClose(handle);
    }

    if (RemoveDirectoryA(path.c_str()) != 0) return true;
    return GetLastError() == ERROR_FILE_NOT_FOUND;
}
#else
bool removeDirectoryRecursive(const std::string& path) {
    DIR* dir = opendir(path.c_str());
    if (!dir) return rmdir(path.c_str()) == 0;

    dirent* entry = nullptr;
    while ((entry = readdir(dir)) != nullptr) {
        const std::string name = entry->d_name;
        if (name == "." || name == "..") continue;

        const std::string fullPath = joinPath(path, name);
        struct stat st;
        if (stat(fullPath.c_str(), &st) != 0) {
            closedir(dir);
            return false;
        }

        if ((st.st_mode & S_IFDIR) != 0) {
            if (!removeDirectoryRecursive(fullPath)) {
                closedir(dir);
                return false;
            }
        }
        else {
            if (std::remove(fullPath.c_str()) != 0) {
                closedir(dir);
                return false;
            }
        }
    }

    closedir(dir);
    return rmdir(path.c_str()) == 0;
}
#endif

bool startsWithKeyword(const std::string& sql, const std::string& keyword) {
    if (sql.size() < keyword.size()) return false;
    return toUpper(sql.substr(0, keyword.size())) == keyword;
}
}

BackupManager::BackupManager() : fileManager(&FileManager::getInstance()) {}

BackupManager& BackupManager::getInstance() {
    static BackupManager instance;
    return instance;
}

bool BackupManager::backupDatabase(const std::string& dbName, const std::string& filePath) {
    const std::string dbPath = DatabaseManager::getInstance().getDBPath(dbName);
    if (dbPath.empty()) {
        std::cout << "Err: database does not exist\n";
        return false;
    }

    std::ofstream ofs(filePath, std::ios::trunc);
    if (!ofs.is_open()) {
        std::cout << "Err: cannot open backup file\n";
        return false;
    }

    ofs << "-- logical backup generated by database_412\n";
    ofs << "-- source database: " << dbName << "\n";
    ofs << "CREATE DATABASE " << dbName << ";\n";
    ofs << "USE " << dbName << ";\n\n";

    const auto tables = loadTables(dbName);
    for (const auto& table : tables) {
        const std::string tableName = table.name;
        ofs << "CREATE TABLE " << tableName << ";\n";

        const auto fields = loadFields(dbName, tableName);
        for (const auto& field : fields) {
            ofs << "ALTER TABLE " << tableName << " ADD " << field.name << " "
                << fieldTypeToSql(field);
            if ((field.flags & FIELD_FLAG_NOT_NULL) != 0) ofs << " NOT NULL";
            ofs << ";\n";
        }

        const auto records = loadRecords(dbName, tableName);
        for (const auto& line : records) {
            const auto values = split(line, '|');
            ofs << "INSERT INTO " << tableName << " VALUES (";
            for (size_t i = 0; i < fields.size(); ++i) {
                const std::string value = i < values.size() ? values[i] : "";
                ofs << quoteSqlValue(value);
                if (i + 1 < fields.size()) ofs << ", ";
            }
            ofs << ");\n";
        }

        ofs << "\n";
    }

    std::cout << "OK: backup completed -> " << filePath << "\n";
    return true;
}

bool BackupManager::restoreDatabase(const std::string& dbName, const std::string& filePath) {
    if (DatabaseManager::getInstance().isDBExists(dbName)) {
        std::cout << "Err: target database already exists\n";
        return false;
    }
    if (!FileManager::fileExists(filePath)) {
        std::cout << "Err: backup file does not exist\n";
        return false;
    }
    if (!cleanupDetachedDatabaseDir(dbName)) {
        std::cout << "Err: cleanup old database directory failed\n";
        return false;
    }

    std::ifstream ifs(filePath);
    if (!ifs.is_open()) {
        std::cout << "Err: cannot open backup file\n";
        return false;
    }

    std::string line;
    int lineNo = 0;
    while (std::getline(ifs, line)) {
        ++lineNo;
        trim(line);
        if (line.empty()) continue;
        if (line.rfind("--", 0) == 0) continue;

        if (startsWithKeyword(line, "CREATE DATABASE ")) {
            line = "CREATE DATABASE " + dbName + ";";
        }
        else if (startsWithKeyword(line, "USE ")) {
            line = "USE " + dbName + ";";
        }

        if (!SQLParser::getInstance().execute(line)) {
            std::cout << "Err: restore failed at line " << lineNo << "\n";
            return false;
        }
    }

    std::cout << "OK: restore completed from " << filePath << "\n";
    return true;
}

bool BackupManager::appendLog(const std::string& dbName, const std::string& sql) {
    if (dbName.empty()) return false;

    const std::string logPath = getLogPath(dbName);
    const std::string logDir = getDatabaseDir(dbName);
    if (!directoryExists(logDir)) return false;

    std::ofstream ofs(logPath, std::ios::app);
    if (!ofs.is_open()) return false;

    std::string line = sql;
    trim(line);
    if (!line.empty() && line.back() != ';') line.push_back(';');
    ofs << line << "\n";
    return true;
}

std::string BackupManager::getLogPath(const std::string& dbName) const {
    return joinPath(getDatabaseDir(dbName), dbName + ".log");
}

std::string BackupManager::getDatabaseDir(const std::string& dbName) const {
    return joinPath(joinPath(g_root, "data"), dbName);
}

std::vector<TableInfo> BackupManager::loadTables(const std::string& dbName) const {
    const std::string dbDir = getDatabaseDir(dbName);
    return fileManager->readAllStruct<TableInfo>(joinPath(dbDir, dbName + ".meta"));
}

std::vector<FieldInfo> BackupManager::loadFields(const std::string& dbName, const std::string& tableName) const {
    return fileManager->readAllStruct<FieldInfo>(joinPath(getDatabaseDir(dbName), tableName + ".fld"));
}

std::vector<std::string> BackupManager::loadRecords(const std::string& dbName, const std::string& tableName) const {
    std::vector<std::string> records;
    std::ifstream ifs(joinPath(getDatabaseDir(dbName), tableName + ".rec"));
    std::string line;
    while (std::getline(ifs, line)) {
        if (!line.empty()) records.push_back(line);
    }
    return records;
}

bool BackupManager::cleanupDetachedDatabaseDir(const std::string& dbName) const {
    const std::string path = getDatabaseDir(dbName);
    if (!directoryExists(path)) return true;
    if (DatabaseManager::getInstance().isDBExists(dbName)) return true;
    return removeDirectoryRecursive(path);
}

std::string BackupManager::fieldTypeToSql(const FieldInfo& field) {
    switch (field.type) {
    case DataType::INT:
        return "INT";
    case DataType::DOUBLE:
        return "DOUBLE";
    case DataType::VARCHAR: {
        std::ostringstream oss;
        oss << "VARCHAR(" << field.param << ")";
        return oss.str();
    }
    default:
        return "VARCHAR(255)";
    }
}

std::string BackupManager::quoteSqlValue(const std::string& value) {
    std::string escaped;
    escaped.reserve(value.size() * 2 + 2);
    for (char ch : value) {
        if (ch == '\\' || ch == '\'') escaped.push_back('\\');
        escaped.push_back(ch);
    }
    return "'" + escaped + "'";
}
