-- logical backup generated by database_412
-- source database: recover_src
CREATE DATABASE recover_src;
USE recover_src;

CREATE TABLE t1;
ALTER TABLE t1 ADD id INT NOT NULL;
ALTER TABLE t1 ADD name VARCHAR(20);
INSERT INTO t1 VALUES ('1', 'Tom');
INSERT INTO t1 VALUES ('2', 'Jerry');

